name: build
on:
  push:
    paths-ignore:
      - '.docs/**'
      - '*.md'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        loader: [fabric, neoforge]
      fail-fast: false
    steps:
      - name: checkout repository
        uses: actions/checkout@v5

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'microsoft'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      #      - name: Candy Server Test
      #        run: ./gradlew runCandyServerTest
      #        timeout-minutes: 2

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew ${{ matrix.loader }}:build

      - name: Upload
        uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.loader }}
          path: ${{ matrix.loader }}/build/libs/*.jar

      - name: Upload-slim
        uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.loader }}-slim
          path: |
            ${{ matrix.loader }}/build/libs/*.jar
            !${{ matrix.loader }}/build/libs/*-shadow.jar
            !${{ matrix.loader }}/build/libs/*-sources.jar

#      - name: Publish Release on Gitee
#        uses: nicennnnnnnlee/action-gitee-release@v1.0.5
#        id: create_release
#        with:
#          gitee_owner: Bread-NiceCat
#          gitee_repo: candycraftce
#          gitee_token: ${{ secrets.GITEE_TOKEN }}
#          gitee_tag_name:
#          gitee_release_name: Test v1.0.0
#          gitee_release_body:
#          gitee_target_commitish: master
#          gitee_upload_retry_times: 3
#          gitee_files: |
#            